apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-conversao-temperatura
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: jeanrnascimento/conversao-temperatura:v1
        ports:
        - containerPort: 8080